sudo: required
language: python
services:
  - docker
env:
    DOCKER_COMPOSE_VERSION: 1.10.1
before_install:
- sudo apt-get update
- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
- chmod +x /usr/local/bin/docker-compose
- docker-compose --version
before_script:
- docker-compose build
- docker-compose up -d 
script:
- docker-compose run --rm web python3 manage.py test 
